In [294]:
import numpy as np
import pandas as pd

In [295]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 27, 22, 32],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}
df = pd.DataFrame(data)

In [296]:
df

Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
3    David   32      Houston

In [297]:
df.head()

Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
3    David   32      Houston

In [298]:
df.head(3)

Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago

In [299]:
df.shape

(4, 3)

In [300]:
df = pd.DataFrame(data, columns=['Name', 'Age', 'City', 'Country'])


In [301]:
df.head()

Name  Age         City Country
0    Alice   24     New York     NaN
1      Bob   27  Los Angeles     NaN
2  Charlie   22      Chicago     NaN
3    David   32      Houston     NaN

In [302]:
df = pd.DataFrame(data, columns=['Name', 'Age', 'City', 'Country'], index=['a', 'b', 'c', 'd'])

In [303]:
df

Name  Age         City Country
a    Alice   24     New York     NaN
b      Bob   27  Los Angeles     NaN
c  Charlie   22      Chicago     NaN
d    David   32      Houston     NaN

In [304]:
df['Name']

a      Alice
b        Bob
c    Charlie
d      David
Name: Name, dtype: object

In [305]:
name_column = df['Name']

In [306]:
name_column

a      Alice
b        Bob
c    Charlie
d      David
Name: Name, dtype: object

In [307]:
type(name_column)

pandas.core.series.Series

In [308]:
df.head()

Name  Age         City Country
a    Alice   24     New York     NaN
b      Bob   27  Los Angeles     NaN
c  Charlie   22      Chicago     NaN
d    David   32      Houston     NaN

In [309]:
df.Age

a    24
b    27
c    22
d    32
Name: Age, dtype: int64

In [310]:
df

Name  Age         City Country
a    Alice   24     New York     NaN
b      Bob   27  Los Angeles     NaN
c  Charlie   22      Chicago     NaN
d    David   32      Houston     NaN

In [311]:
df.Country = ['USA', 'USA', 'USA', 'USA']


In [312]:
df

Name  Age         City Country
a    Alice   24     New York     USA
b      Bob   27  Los Angeles     USA
c  Charlie   22      Chicago     USA
d    David   32      Houston     USA

In [313]:
val = pd.Series([1700, 1800, 1750, 1600], index=['a', 'b', 'c', 'd'])
df['Salary'] = val

In [314]:
df

Name  Age         City Country  Salary
a    Alice   24     New York     USA    1700
b      Bob   27  Los Angeles     USA    1800
c  Charlie   22      Chicago     USA    1750
d    David   32      Houston     USA    1600

In [315]:
val = [1700, 1800, 1750, 1600]
df.Salary = val

In [316]:
df

Name  Age         City Country  Salary
a    Alice   24     New York     USA    1700
b      Bob   27  Los Angeles     USA    1800
c  Charlie   22      Chicago     USA    1750
d    David   32      Houston     USA    1600

In [317]:
df['1700+'] = df.Salary > 1700

In [318]:
df

Name  Age         City Country  Salary  1700+
a    Alice   24     New York     USA    1700  False
b      Bob   27  Los Angeles     USA    1800   True
c  Charlie   22      Chicago     USA    1750   True
d    David   32      Houston     USA    1600  False

In [319]:
df['Name'][df['1700+']]

b        Bob
c    Charlie
Name: Name, dtype: object

In [320]:
df

Name  Age         City Country  Salary  1700+
a    Alice   24     New York     USA    1700  False
b      Bob   27  Los Angeles     USA    1800   True
c  Charlie   22      Chicago     USA    1750   True
d    David   32      Houston     USA    1600  False

In [321]:
data = {
    'Uzbekistan':{2021: 100, 2022: 110, 2023: 120},
    'USA':{2021: 200, 2022: 210, 2023: 220},
    'Russia':{2021: 300, 2022: 310, 2023: 320}
}
df2 = pd.DataFrame(data)

In [322]:
df2

Uzbekistan  USA  Russia
2021         100  200     300
2022         110  210     310
2023         120  220     320

In [323]:
df2.index.name = 'Year'
df2.columns.name = 'Country'
df2

Country  Uzbekistan  USA  Russia
Year                            
2021            100  200     300
2022            110  210     310
2023            120  220     320

In [324]:
df2 = pd.DataFrame(data, index=[2021, 2022, 2023])

In [325]:
df2

Uzbekistan  USA  Russia
2021         100  200     300
2022         110  210     310
2023         120  220     320

In [326]:
df2.T

2021  2022  2023
Uzbekistan   100   110   120
USA          200   210   220
Russia       300   310   320

In [327]:
df2.values

array([[100, 200, 300],
       [110, 210, 310],
       [120, 220, 320]])

In [328]:
arr = df2.values

In [329]:
arr

array([[100, 200, 300],
       [110, 210, 310],
       [120, 220, 320]])

In [330]:
type(arr)

numpy.ndarray

In [331]:
df2.index

Index([2021, 2022, 2023], dtype='int64')

In [332]:
df

Name  Age         City Country  Salary  1700+
a    Alice   24     New York     USA    1700  False
b      Bob   27  Los Angeles     USA    1800   True
c  Charlie   22      Chicago     USA    1750   True
d    David   32      Houston     USA    1600  False

In [333]:
df.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [334]:
df.columns

Index(['Name', 'Age', 'City', 'Country', 'Salary', '1700+'], dtype='object')

In [335]:
indeks = df.columns

In [336]:
indeks

Index(['Name', 'Age', 'City', 'Country', 'Salary', '1700+'], dtype='object')

In [337]:
'Temp' in indeks

False

In [338]:
df2

Uzbekistan  USA  Russia
2021         100  200     300
2022         110  210     310
2023         120  220     320

In [339]:
'Tajikistan' in df2.columns

False

In [340]:
'USA' in df2.columns

True

In [341]:
2021 in df2

False

In [342]:
indeks

Index(['Name', 'Age', 'City', 'Country', 'Salary', '1700+'], dtype='object')

In [343]:
indeks[0]

'Name'

In [344]:
indeks[2:4]

Index(['City', 'Country'], dtype='object')

In [345]:
indeks[0]="qiymat"

TypeError: Index does not support mutable operations

In [346]:
df

Name  Age         City Country  Salary  1700+
a    Alice   24     New York     USA    1700  False
b      Bob   27  Los Angeles     USA    1800   True
c  Charlie   22      Chicago     USA    1750   True
d    David   32      Houston     USA    1600  False

In [347]:
usernames={"Bob": "bob123", "Alice": "alice_w", "Charlie": "charlie89", "David": "david_d"}
emails = {"Bob": "bob@example.com", "Alice": "alice@example.com", "Charlie": "charlie@example.com", "David": "david@example.com"}

data = {
    'Username': usernames,
    'Email': emails
}

df = pd.DataFrame(data)

In [348]:
df

Username                Email
Bob         bob123      bob@example.com
Alice      alice_w    alice@example.com
Charlie  charlie89  charlie@example.com
David      david_d    david@example.com

In [349]:
df.index

Index(['Bob', 'Alice', 'Charlie', 'David'], dtype='object')

In [350]:
arr = ['Bob', 'Alice', 'Charlie', 'David']

In [351]:
arr[0]

'Bob'

In [352]:
arr[3]

'David'

In [353]:
arr[1]

'Alice'

In [367]:
data2 = {
    'username':{"Bob": "bob123", "Alice": "alice_w", "Charlie": "charlie89", "David": "david_d"},
    'email':{"Bob": "bob@example.com", "Alice": "alice@example.com", "Charlie": "charlie@example.com", "David": "david@example.com"}
}

In [368]:
data2

{'username': {'Bob': 'bob123',
  'Alice': 'alice_w',
  'Charlie': 'charlie89',
  'David': 'david_d'},
 'email': {'Bob': 'bob@example.com',
  'Alice': 'alice@example.com',
  'Charlie': 'charlie@example.com',
  'David': 'david@example.com'}}

In [370]:
df2 = pd.DataFrame(data2)
df2

username                email
Bob         bob123      bob@example.com
Alice      alice_w    alice@example.com
Charlie  charlie89  charlie@example.com
David      david_d    david@example.com

In [371]:
newind = pd.Index(['Bob', 'Alice', 'Charlie', 'David'])
newind

Index(['Bob', 'Alice', 'Charlie', 'David'], dtype='object')

In [372]:
newind.isin(['Alice', 'David'])

array([False,  True, False,  True])

In [373]:
df2.index.difference(newind)

Index([], dtype='object')

In [375]:
newind.difference(df2.index)

Index([], dtype='object')

In [376]:
df2.index.union(newind)

Index(['Bob', 'Alice', 'Charlie', 'David'], dtype='object')

In [378]:
df2.index.delete(0)

Index(['Alice', 'Charlie', 'David'], dtype='object')

In [379]:
newind

Index(['Bob', 'Alice', 'Charlie', 'David'], dtype='object')